[accounts.gmail]
email = "jhodsko08@gmail.com"
display-name = "jhodsko08"
default = true

backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.encryption.type = "tls"
backend.login = "jhodsko08@gmail.com"
backend.auth.type = "password"
backend.auth.raw = "Jezy@2173"

message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 587
message.send.backend.encryption.type = "start-tls"
message.send.backend.login = "jhodsko08@gmail.com"
message.send.backend.auth.type = "password"
message.send.backend.auth.raw = "Jezy@2173"
